### ISSUE TITLE
hitchwiki history

### ISSUE THREAD

**Issue by guaka** [trustroots-community/trustrots#10]
I don't understand the relevance of mentioning the Hitchwiki Hackathon in Turkey, could be good to point out why it could be relevant to the story.

More importantly, since Hitchwiki is mentioned and Hitchwiki is a progenitor of Trustroots, I think it's useful to refer to this: https://hitchwiki.org/en/Hitchwiki:About#Background

**Comment by mrkvon** [comment]
Hello @guaka, thank you for opening the issue and welcome to this repository.

First of all, i'm currently not sharing this site beyond closest friends. I feel a need to publish some information, but i'd prefer to share a version which makes our future communication feasible, especially something that other volunteers can agree on as well.

Mentioning Hitchwiki hackathon is more of a personal memory. That's where I met Mikael, Arthur, Rémi, Simona, ... for the first time, and they were actively finishing first version of Trustroots before release.

**Comment by mrkvon** [comment]
I linked the [Hitchwiki about page](https://hitchwiki.org/en/Hitchwiki:About) (without the fragment) and provided info why the hackathon is mentioned. Does that work for you @guaka?
