### ISSUE TITLE
Robin was fired

### ISSUE THREAD

**Issue by chmac** [trustroots-community/trustrots#2]
Robin was fired from the core team.

**Comment by mrkvon** [comment]
> Robin was fired from the core team.

Interesting claim. What's the "core team"? Has there ever been an employment relationship between Robin and Trustroots organization? Who fired him, why, when, and by what authority? Can you provide details and evidence? 🤔

Also, how is it relevant for this repository?

Closing this as not relevant. Will reopen if sufficient information proving contrary is provided.

**Comment by chmac** [comment]
The relevance is that you encourage people to write to Robin, but he's no longer actively involved in decision making.

**Comment by mrkvon** [comment]
That's a good point. If that's indeed the case, i'll update the repo.

To be able to proceed, i need this claim to be substantiated. Thank you for your cooperation.
