### ISSUE TITLE
Missing email down for 5 weeks

### ISSUE THREAD

**Issue by chmac** [trustroots-community/trustrots#6]
The timeline is great by the way. A little inaccurate and somewhat sloppy, but nice to see the history from your point of view.

But it seems remiss to omit the fact that the site was essentially useless for five weeks because email wasn't working.

**Comment by mrkvon** [comment]
> [...] A little inaccurate and somewhat sloppy, [...]

Please refrain from providing vague labels undermining the work.

> it seems remiss to omit the fact that the site was essentially useless for five weeks because email wasn't working

Whether to include technical difficulties is a matter of preference. We can't include every time that the site was down or email not working.

Anyways, can you provide dates of start and end, reference, and why you think the event should be there? If it's reasonable, we'll consider including it.

**Comment by chmac** [comment]
Hehe, I find your use of "we" entertaining.

Again, I'm not in the business of providing you with information you can yourself retrieve. I'm only trying to point out the gross inaccuracies in your representation of history, fixing them is up to you.

**Comment by guaka** [comment]
Please check these graphs:

https://grafana.trustroots.org/d/000000002/members?orgId=1&from=now-2y&to=now

https://grafana.trustroots.org/d/000000004/messages-detailed?orgId=1&refresh=15m&from=now-2y&to=now

<img width="417" alt="image" src="https://github.com/trustroots-community/trustrots/assets/54728/cc98573d-7afd-4d7e-9f85-647f1e9aa62c">

<img width="599" alt="image" src="https://github.com/trustroots-community/trustrots/assets/54728/36a59808-c3ab-4078-9605-481ee6418938">

I'll leave it to everyone's imagination what would have happened if emails would not have been restored.

**Comment by mrkvon** [comment]
Thank you @guaka.
